export default Object.freeze({
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_MALFORMED: "TOKEN_MALFORMED",
  TOKEN_TEMPERED: "TOKEN_TEMPERED",
  TOKEN_NOT_BEGIN_WITH_BEARER: "TOKEN_NOT_BEGIN_WITH_BEARER",
  UNAUTHORIZED_UPDATE: "UNAUTHORIZED_UPDATE",
  AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
})