name: SSH Tunnel
on:
  workflow_run:
    workflows: ["Build and Push docker image"]
    branches: [main, "CI/CD"]
    types: 
      - completed

jobs:
  deploy:
    name: Set up tunnel
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup tunnel
      uses: joshlarsen/ssh-tunnel-action@main
      with:
        timeout: 1h
        ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        ngrok_token: ${{ secrets.NGROK_TOKEN }}
